# Generated by Django 3.1.7 on 2021-08-12 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('customerprofile', models.CharField(max_length=100)),
                ('loanaccountno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanAmountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreementdate', models.DateField()),
                ('lrn', models.CharField(max_length=100)),
                ('tenor', models.CharField(max_length=100)),
                ('advemi', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanamt', to='apps.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOfficeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officepincode', models.IntegerField()),
                ('officelandmark', models.CharField(max_length=500)),
                ('ofcaddress1', models.CharField(max_length=500)),
                ('ofcaddress2', models.CharField(max_length=500)),
                ('ofcaddress3', models.CharField(max_length=500)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custoffdata', to='apps.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHomeAddressData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('address3', models.CharField(max_length=500)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custhomeadd', to='apps.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BranchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zonename', models.CharField(max_length=100)),
                ('regionname', models.CharField(max_length=100)),
                ('areaname', models.CharField(max_length=100)),
                ('branchname', models.CharField(max_length=100)),
                ('branchcode', models.CharField(max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='apps.customer')),
            ],
        ),
    ]
